# 基础镜像
FROM redis:7.0.0
# author
MAINTAINER twelvet

# 挂载目录
VOLUME /home/twelvet/redis
# 创建目录
RUN mkdir -p /home/twelvet/redis
# 指定路径
WORKDIR /home/twelvet/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/twelvet/redis/redis.conf
