# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER twelvet

# 挂载目录
VOLUME /home/twelvet
# 创建目录
RUN mkdir -p /home/twelvet
# 指定路径
WORKDIR /home/twelvet
# 复制jar文件到路径
COPY ./jar/twelvet-gateway.jar /home/twelvet/twelvet-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","twelvet-gateway.jar"]