# 基础镜像
FROM nginx
# author
MAINTAINER twelvet

# 挂载目录
VOLUME /home/twelvet/projects/twelvet-ui
# 创建目录
RUN mkdir -p /home/twelvet/projects/twelvet-ui
# 指定路径
WORKDIR /home/twelvet/projects/twelvet-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html /home/twelvet/projects/twelvet-ui
