# 指定基础镜像
FROM anapsix/alpine-java
LABEL maintainer="2471835953@qq.com"
# 挂载目录
VOLUME /home/twelvet
# 创建目录
RUN mkdir -p /home/twelvet
# 指定路径
WORKDIR /home/twelvet
# 复制jar文件到路径
COPY ./jar/twelvet-server-dfs.jar /home/twelvet/twelvet-server-dfs.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","twelvet-server-dfs.jar"]
