# 基础镜像
FROM mysql/mysql-server:8.0.32
# author
MAINTAINER twelvet

ENV TZ=Asia/Shanghai

RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 执行sql脚本
COPY ./db/twelvet_nacos.sql /docker-entrypoint-initdb.d/
COPY ./db/twelvet.sql /docker-entrypoint-initdb.d/
