# 指定基础镜像
FROM openjdk:17-oracle
LABEL maintainer="2471835953@qq.com"
# 创建目录
RUN mkdir -p /home/twelvet
# 指定路径
WORKDIR /home/twelvet
# 复制jar文件到路径
COPY ./target/*.jar /home/twelvet/twelvet-gateway.jar
# 启动网关服务
ENV TZ=Asia/Shanghai JAVA_OPTS="-Xms128m -Xmx256m -Djava.security.egd=file:/dev/./urandom"
EXPOSE 8080
CMD java -DNACOS_HOST=nacos.middleware -jar twelvet-gateway.jar