FROM openjdk:8-jdk


#启动自行加载   服务名-prod.yml配置
ENV PARAMS="--server.port=8080 -Xms512m -Xmx2048m"
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

COPY target/*.jar /twelvet-gateway.jar
EXPOSE 8080

#
ENTRYPOINT ["/bin/sh","-c","java -Djava.security.egd=file:/dev/./urandom -jar /twelvet-gateway.jar ${PARAMS}"]